name: bikeshare_cdmx_streamlit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23
  - pandas=1.5
  - matplotlib
  - geopandas
  - shapely
  - pyproj
  - fiona
  - folium
  - branca
  - jupyter
  - streamlit
  - pip
  - geopy
  - pip:
      - streamlit-folium
      - altair
